import json

# 读取本地 JSON 文件
with open("openqa_answer.json", "r", encoding="utf-8") as f:
    data = json.load(f)

output = []

for video_name, content in data.items():
    primary_answer = content["primary_answer"]
    alternative_answers = content["alternative_answers"]
    
    # 使用视频文件名作为图像路径（假设扩展名改为.jpg或.png）
    video_path = f"impossible_videos/{video_name}"
    
    # 第一组提示词：AI-generated
    messages_ai = [
        {
            "role": "user",
            "content": "<video>\nYou have been shown one video, which might be taken from real world or generated by an advanced AI model. \nIs this video generated by an AI model? (Answer yes if you think it is synthesized by an AI model, and answer no otherwise.)\n."
        },
        {
            "role": "assistant",
            # "content": f"Yes. {primary_answer}"
            "content": f"Yes. This video contains logic inconsistency and is AI-generated. {primary_answer}"
        }
    ]
    
    # 第二组提示词：not from the real world
    messages_not_real = [
        {
            "role": "user",
            "content": "<video>\nYou have been shown one video, which might be taken from real world or generated by an advanced AI model. \nIs this video taken in the real world? (Answer yes if you think it is taken in the real world, and answer no otherwise.)\n"
        },
        {
            "role": "assistant",
            # "content": f"No. {primary_answer}"
            "content": f"No. This video contains logic inconsistency and is not from the real world. {primary_answer}"
        }
    ]
    
    output.append({
        "messages": messages_ai,
        "videos": [video_path]
    })
    
    output.append({
        "messages": messages_not_real,
        "videos": [video_path]
    })


# 写入 sharegpt 格式的 json 文件
with open("/data/LLaMA-Factory/data/ipv.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print("转换完成 ✅")
print(f"总共生成条目数: {len(output)}")