import json
import csv
import os
import random

# ====== 1. Prepare the video datasets ======

# Load synthetic videos (from openqa_answer.json)
with open("openqa_answer.json", "r", encoding="utf-8") as f:
    synthetic_data = json.load(f)

synthetic_videos = []
for video_name, content in synthetic_data.items():
    primary_answer = content["primary_answer"]
    video_path = f"impossible_videos/{video_name}"
    synthetic_videos.append({
        "path": video_path,
        "answer": primary_answer,
        "type": "synthetic"
    })

# Load real videos (from OpenVid_part100.csv and OpenVid-1M.csv)
video_paths = {}
with open("OpenVid_part100.csv", "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        video = row["video"]
        video_path = row["video_path"]
        video_paths[video] = f"OpenVid_part100/{video_path}"

captions = {}
with open("OpenVid-1M.csv", "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        video = row["video"]
        caption = row["caption"]
        captions[video] = caption

real_videos = []
for video, path in video_paths.items():
    caption = captions.get(video, "").strip()
    if caption:
        real_videos.append({
            "path": path,
            "answer": caption,
            "type": "real"
        })

# ====== 2. Create random pairs ======
random.shuffle(synthetic_videos)
random.shuffle(real_videos)

pairs = []
for i in range(899):
    if i >= len(synthetic_videos) or i >= len(real_videos):
        break
    
    # Randomly decide which video comes first (50/50 chance)
    if random.random() < 0.5:
        video1 = synthetic_videos[i]
        video2 = real_videos[i]
        correct_answer = "B"  # For "which is real" question
        correct_answer_ai = "A"  # For "which is AI" question
    else:
        video1 = real_videos[i]
        video2 = synthetic_videos[i]
        correct_answer = "A"
        correct_answer_ai = "B"
    
    pairs.append({
        "video1": video1,
        "video2": video2,
        "correct_answer": correct_answer,
        "correct_answer_ai": correct_answer_ai
    })

# ====== 3. Generate comparison questions ======
output = []

for pair in pairs:
    video1 = pair["video1"]
    video2 = pair["video2"]
    
import random

# Question 1: Which is real?
messages_real = [
    {
        "role": "user", 
        "content": "<video>\n<video>\nYou have been shown two different videos. One of the videos is generated by AI, while the other is taken in the real world. Which of the above videos is most likely taken in the real world?\nA. The first one.\nB. The second one.\nAnswer with the option letter."
    },
    {
        "role": "assistant",
        "content": f"{pair['correct_answer']}. The {'first' if pair['correct_answer'] == 'A' else 'second'} video is taken in the real world: {video1['answer'] if pair['correct_answer'] == 'A' else video2['answer']}"
    }
]

# Question 2: Which is AI?
# Randomly decide whether to swap the videos (50% chance)
swap_videos = random.random() < 0.5

if swap_videos:
    # Swap the videos and adjust the answer accordingly
    messages_ai = [
        {
            "role": "user", 
            "content": "<video>\n<video>\nYou have been shown two different videos. One of the videos is taken in the real world, while the other is generated by an advanced AI model. Which of the above videos is most likely generated by AI?\nA. The first one.\nB. The second one.\nAnswer with the option letter."
        },
        {
            "role": "assistant",
            "content": f"{'B' if pair['correct_answer_ai'] == 'A' else 'A'}. The {'first' if pair['correct_answer_ai'] == 'B' else 'second'} video is generated by AI: {video2['answer'] if pair['correct_answer_ai'] == 'A' else video1['answer']}"
        }
    ]
    video_paths_ai = [video2["path"], video1["path"]]
else:
    messages_ai = [
        {
            "role": "user", 
            "content": "<video>\n<video>\nYou have been shown two different videos. One of the videos is taken in the real world, while the other is generated by an advanced AI model. Which of the above videos is most likely generated by AI?\nA. The first one.\nB. The second one.\nAnswer with the option letter."
        },
        {
            "role": "assistant",
            "content": f"{pair['correct_answer_ai']}. The {'first' if pair['correct_answer_ai'] == 'A' else 'second'} video is generated by AI: {video1['answer'] if pair['correct_answer_ai'] == 'A' else video2['answer']}"
        }
    ]
    video_paths_ai = [video1["path"], video2["path"]]

output.append({
    "messages": messages_real,
    "videos": [video1["path"], video2["path"]]
})

output.append({
    "messages": messages_ai,
    "videos": video_paths_ai
})

# ====== 4. Save to mc.json ======
with open("/data/LLaMA-Factory/data/mc.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print("转换完成 ✅")
print(f"总共生成条目数: {len(output)}")
print(f"视频配对数量: {len(pairs)}")