import json

# 读取本地 train.json
with open("train.json", "r", encoding="utf-8") as f:
    data = json.load(f)

output = []

for item in data:
    entry = list(item.values())[0]
    
    caption = entry["caption"]
    image_path = f"synthscars/{entry['img_file_name']}"
    
    # 第一组提示词：AI-generated
    messages_ai = [
        {
            "role": "user",
            "content": "<image>\nYou have been shown one image, which might be taken from real world or generated by an advanced AI model. \nIs this video generated by an AI model? (Answer yes if you think it is synthesized by an AI model, and answer no otherwise.)\n."
        },
        {
            "role": "assistant",
            "content": f"Yes. {caption}"
        }
    ]
    # 第二组提示词：not from the real world
    messages_not_real = [
        {
            "role": "user",
            "content": "<image>\nYou have been shown one image, which might be taken from real world or generated by an advanced AI model. \nIs this video taken in the real world? (Answer yes if you think it is taken in the real world, and answer no otherwise.)\n"
        },
        {
            "role": "assistant",
            "content": f"No. {caption}"
        }
    ]

    
    output.append({
        "messages": messages_ai,
        "images": [image_path]
    })
    
    output.append({
        "messages": messages_not_real,
        "images": [image_path]
    })



# 写入 sharegpt 格式的 json 文件
with open("/data/LLaMA-Factory/data/synthscars.json", "w", encoding="utf-8") as f:
    json.dump(output, f, indent=2, ensure_ascii=False)

print("转换完成 ✅")
print(f"总共生成条目数: {len(output)}")

